import { School, Student, MessageItem, TermEvent, ShopItem, ClubBooking, ConsentRequest, Transaction } from '../types';

export const mockSchools: School[] = [
  {
    id: 'sch-001',
    name: 'The Woodlands School',
    code: 'TWS',
    address: 'Nethermayne, Basildon SS16 5NN',
    phone: '01268 282146',
    email: 'catering@woodlands.school.uk',
    lunch_cutoff_day: 'Thursday',
    lunch_cutoff_time: '23:59',
    meal_price: 2.70,
    weekly_price: 13.50,
  },
  {
    id: 'sch-002',
    name: 'St. Mary Primary Academy',
    code: 'SMPA',
    address: 'High Street, Chelmsford CM1 1AA',
    phone: '01245 491234',
    email: 'admin@stmary.school.uk',
    lunch_cutoff_day: 'Wednesday',
    lunch_cutoff_time: '23:59',
    meal_price: 2.70,
    weekly_price: 13.50,
  }
];

export const mockStudents: Student[] = [
  {
    id: 'stu-001',
    parent_id: 'par-001',
    school_id: 'sch-001',
    school_name: 'The Woodlands School',
    first_name: 'Oliver',
    last_name: 'Bennett',
    year_group: 'Year 4',
    class_name: '4B Beech Class',
    dietary_requirements: 'Nut Allergy (Mild)',
    allergies: ['Peanuts'],
    requires_halal: false,
    menu_profile: 'main',
    dinner_credit: 0.00,
    club_credit: 0.00,
  }
];

// Week data is now provided by dailyMenuData.ts

export const mockMenuItems: any[] = [
  // W/C 31 Aug 2026 - Monday
  {
    id: 'menu-31aug-mon-1',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Monday',
    title: 'Hobbs Artisan Pork Sausage & Creamy Mash with Onion Gravy',
    category: 'Main',
    description: 'Farm-assured British sausages with homemade Yukon gold mash & sweet garden peas.',
    price: 2.65,
    allergens: ['Gluten', 'Sulphites'],
    is_active: true,
  },
  {
    id: 'menu-31aug-mon-2',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Monday',
    title: 'Veggie Cumberland Sausage with Mash (V)',
    category: 'Vegetarian',
    description: 'Plant-based herb sausage served with buttery mash and steamed sweetcorn.',
    price: 2.65,
    allergens: ['Gluten', 'Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-mon-3',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Monday',
    title: 'Jacket Potato with Cheddar & Baked Beans (GF)',
    category: 'Jacket Potato',
    description: 'Slow-baked British jacket potato with vintage cheddar cheese & Heinz baked beans.',
    price: 2.65,
    allergens: ['Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-mon-4',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Monday',
    title: 'Hobbs Deli Baguette (Tuna & Sweetcorn)',
    category: 'Deli / Packed Lunch',
    description: 'Freshly baked wholemeal baguette with dolphin-friendly tuna & sweetcorn salad.',
    price: 2.65,
    allergens: ['Fish', 'Gluten', 'Eggs'],
    is_active: true,
  },

  // Tuesday
  {
    id: 'menu-31aug-tue-1',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Tuesday',
    title: 'Mild Chicken Tikka Masala with Fragrant Basmati Rice',
    category: 'Main',
    description: 'Tender British chicken breast in a mild coconut & tomato curry sauce.',
    price: 2.65,
    allergens: ['Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-tue-2',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Tuesday',
    title: 'Sweet Potato & Chickpea Korma with Rice (V)',
    category: 'Vegetarian',
    description: 'Roasted sweet potatoes, chickpeas and spinach in a lightly spiced aromatic sauce.',
    price: 2.65,
    allergens: [],
    is_active: true,
  },
  {
    id: 'menu-31aug-tue-3',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Tuesday',
    title: 'Jacket Potato with Tuna Mayo',
    category: 'Jacket Potato',
    description: 'Oven-baked potato filled with creamy tuna mayonnaise & crunchy cucumber sticks.',
    price: 2.65,
    allergens: ['Fish', 'Eggs'],
    is_active: true,
  },

  // Wednesday (Roast Day)
  {
    id: 'menu-31aug-wed-1',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Wednesday',
    title: 'Roast British Beef & Yorkshire Pudding with Crisp Roasties',
    category: 'Main',
    description: 'Succulent sliced roast beef, golden roast potatoes, honey carrots, broccoli & rich gravy.',
    price: 2.65,
    allergens: ['Gluten', 'Eggs', 'Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-wed-2',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Wednesday',
    title: 'Butternut Squash & Spinach Wellington (V)',
    category: 'Vegetarian',
    description: 'Flaky golden puff pastry roll filled with roasted butternut squash and feta.',
    price: 2.65,
    allergens: ['Gluten', 'Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-wed-3',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Wednesday',
    title: 'Jacket Potato with Baked Beans & Cheese',
    category: 'Jacket Potato',
    description: 'Fluffy baked potato with grated Red Leicester and Heinz beans.',
    price: 2.65,
    allergens: ['Milk'],
    is_active: true,
  },

  // Thursday
  {
    id: 'menu-31aug-thu-1',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Thursday',
    title: 'Traditional Beef Lasagne with Garlic Ciabatta',
    category: 'Main',
    description: 'Slow-cooked lean minced beef ragu layered with egg pasta & bechamel sauce.',
    price: 2.65,
    allergens: ['Gluten', 'Milk', 'Eggs'],
    is_active: true,
  },
  {
    id: 'menu-31aug-thu-2',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Thursday',
    title: 'Mediterranean Vegetable Lasagne (V)',
    category: 'Vegetarian',
    description: 'Roasted courgettes, aubergines, peppers and tomato ragu with crisp green salad.',
    price: 2.65,
    allergens: ['Gluten', 'Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-thu-3',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Thursday',
    title: 'Hobbs Deli Baguette (Mild Cheddar & Salad)',
    category: 'Deli / Packed Lunch',
    description: 'Crusty roll with British cheddar, crisp lettuce and sliced ripe tomatoes.',
    price: 2.65,
    allergens: ['Gluten', 'Milk'],
    is_active: true,
  },

  // Friday (Fish Friday)
  {
    id: 'menu-31aug-fri-1',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Friday',
    title: 'Crispy Breaded MSC Cod Fillet with Chunky Oven Chips',
    category: 'Main',
    description: 'Sustainably sourced cod in crunchy golden crumb, garden peas and homemade tartar.',
    price: 2.65,
    allergens: ['Fish', 'Gluten'],
    is_active: true,
  },
  {
    id: 'menu-31aug-fri-2',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Friday',
    title: 'Golden Cheesy Pizza Whirl with Chunky Chips (V)',
    category: 'Vegetarian',
    description: 'Fresh dough pinwheel with Italian herbs, tomato passata and melted mozzarella.',
    price: 2.65,
    allergens: ['Gluten', 'Milk'],
    is_active: true,
  },
  {
    id: 'menu-31aug-fri-3',
    school_id: 'sch-001',
    week_commencing: '2026-08-31',
    day_of_week: 'Friday',
    title: 'Jacket Potato with Heinz Baked Beans',
    category: 'Jacket Potato',
    description: 'Healthy baked potato with hearty baked beans.',
    price: 2.65,
    allergens: [],
    is_active: true,
  },
];

export const mockMessages: MessageItem[] = [
  {
    id: 'msg-001',
    school_id: 'sch-001',
    title: 'Urgent: Lunch order deadline for January term',
    body: "You haven't ordered your child's lunches for the first week back in January yet. Please order these by tomorrow morning otherwise you will miss the cut off.",
    type: 'reminder',
    urgency: 'high',
    is_new: true,
    date_formatted: '10:25, 17 December 2025',
    created_at: '2025-12-17T10:25:00Z',
  },
  {
    id: 'msg-002',
    school_id: 'sch-001',
    title: 'Lunch order reminder: November return',
    body: 'Lunch order reminder: Today is the last day to place an order ready for when we return on the 3rd November.',
    type: 'reminder',
    urgency: 'normal',
    is_new: true,
    date_formatted: '08:31, 30 October 2025',
    created_at: '2025-10-30T08:31:00Z',
  },
  {
    id: 'msg-003',
    school_id: 'sch-001',
    title: 'School Closure: Planned INSET day',
    body: 'Good Morning, A gentle reminder that the school will be closed to all students on Friday 11th July as it is a planned inset day for teacher training.',
    type: 'closure',
    urgency: 'normal',
    is_new: true,
    date_formatted: '09:38, 09 July 2025',
    created_at: '2025-07-09T09:38:00Z',
  },
  {
    id: 'msg-004',
    school_id: 'sch-001',
    title: 'Early Closing: Hazeley Campus',
    body: 'Good morning, A kind reminder that The Woodlands School, Hazeley Campus will be closing today at 12:45pm.',
    type: 'notice',
    urgency: 'low',
    is_new: false,
    date_formatted: '08:15, 20 June 2025',
    created_at: '2025-06-20T08:15:00Z',
  },
];

export const mockTermEvents: TermEvent[] = [
  {
    id: 'term-001',
    school_id: 'sch-001',
    title: 'Autumn Term 2026 Begins',
    event_date: '2026-09-02',
    category: 'term',
    description: 'First day of academic year 2026/2027.',
  },
  {
    id: 'term-002',
    school_id: 'sch-001',
    title: 'Teacher Training INSET Day (School Closed)',
    event_date: '2026-10-23',
    category: 'inset_day',
    description: 'School closed to all pupils.',
  },
  {
    id: 'term-003',
    school_id: 'sch-001',
    title: 'October Half Term Holiday',
    event_date: '2026-10-26',
    end_date: '2026-10-30',
    category: 'holiday',
    description: 'Autumn half term break.',
  },
  {
    id: 'term-004',
    school_id: 'sch-001',
    title: 'Hobbs Christmas Festive Dinner Day',
    event_date: '2026-12-16',
    category: 'event',
    description: 'Special Christmas dinner menu with turkey roast, crackers and pudding!',
  }
];

export const mockShopItems: ShopItem[] = [
  {
    id: 'shp-001',
    school_id: 'sch-001',
    name: 'Woodlands School Embroidered V-Neck Jumper',
    description: 'Durable cotton/acrylic mix with high-definition school crest embroidery. Machine washable.',
    category: 'Uniform',
    price: 14.95,
    in_stock: true,
  },
  {
    id: 'shp-002',
    school_id: 'sch-001',
    name: 'Hobbs Stainless Steel Insulated Water Bottle (500ml)',
    description: 'BPA-free, double-wall insulated bottle with leak-proof sports cap.',
    category: 'Accessories',
    price: 6.50,
    in_stock: true,
  },
  {
    id: 'shp-003',
    school_id: 'sch-001',
    name: 'Woodlands PE Kit Gym Bag (Waterproof)',
    description: 'Drawstring gym bag with reinforced corners and reflective safety strips.',
    category: 'Accessories',
    price: 5.00,
    in_stock: true,
  },
  {
    id: 'shp-004',
    school_id: 'sch-001',
    name: 'Hobbs Lunch Card Replacement Pass',
    description: 'Replacement contactless student meal card with lanyard.',
    category: 'Meal Vouchers',
    price: 3.00,
    in_stock: true,
  }
];

export const mockClubBookings: ClubBooking[] = [
  {
    id: 'clb-001',
    student_id: 'stu-001',
    school_id: 'sch-001',
    club_name: 'Hobbs Healthy Breakfast Club',
    session_date: '2026-09-07',
    time_slot: '07:45 - 08:45 AM',
    price: 4.00,
    status: 'confirmed',
  },
  {
    id: 'clb-002',
    student_id: 'stu-001',
    school_id: 'sch-001',
    club_name: 'Woodlands After-School Athletics Club',
    session_date: '2026-09-08',
    time_slot: '15:15 - 16:30 PM',
    price: 5.50,
    status: 'confirmed',
  }
];

export const mockConsentRequests: ConsentRequest[] = [
  {
    id: 'con-001',
    student_id: 'stu-001',
    school_id: 'sch-001',
    title: 'Hobbs Catering Dietary & Allergen Confirmation (2026/27)',
    description: 'Please confirm that the listed allergy records (Peanuts, Tree Nuts) and emergency dietary guidelines remain accurate for your child.',
    due_date: '2026-09-15',
    status: 'pending',
  },
  {
    id: 'con-002',
    student_id: 'stu-001',
    school_id: 'sch-001',
    title: 'Year 4 Colchester Castle Educational Field Trip',
    description: 'Permission for Oliver to travel via coach and participate in museum workshops.',
    due_date: '2026-10-10',
    status: 'granted',
    granted_at: '2026-08-15T14:22:00Z',
    granted_by: 'Parent/Guardian (Online)',
  }
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    student_id: 'stu-001',
    student_name: 'Oliver Bennett',
    type: 'meal_payment',
    title: 'School Meals: W/C 24 Aug (5 Lunches)',
    amount: 13.50,
    status: 'completed',
    payment_method: 'Debit Card (ending in 4421)',
    reference: 'HBS-PAY-882910',
    created_at: '2026-08-18T11:42:00Z',
    date_formatted: '18 Aug 2026 11:42',
  },
  {
    id: 'tx-002',
    student_id: 'stu-001',
    student_name: 'Oliver Bennett',
    type: 'credit_topup',
    title: 'Account Balance Top Up',
    amount: 25.00,
    status: 'completed',
    payment_method: 'Apple Pay',
    reference: 'HBS-TOP-551029',
    created_at: '2026-08-01T09:15:00Z',
    date_formatted: '01 Aug 2026 09:15',
  },
  {
    id: 'tx-003',
    student_id: 'stu-001',
    student_name: 'Oliver Bennett',
    type: 'club_fee',
    title: 'Breakfast Club (Autumn Term Pass)',
    amount: 20.00,
    status: 'completed',
    payment_method: 'Debit Card (ending in 4421)',
    reference: 'HBS-CLB-990214',
    created_at: '2026-07-28T16:03:00Z',
    date_formatted: '28 Jul 2026 16:03',
  }
];

export const mockMealBookings: any[] = [
  {
    id: 'mbk-001',
    student_id: 'stu-001',
    menu_item_id: 'menu-31aug-mon-1',
    booking_date: '2026-08-31',
    day_of_week: 'Monday',
    meal_title: 'Hobbs Artisan Pork Sausage & Mash',
    category: 'Option 1',
    price: 2.70,
    status: 'booked',
    paid: true,
    created_at: '2026-08-20T10:00:00Z',
  }
];
